// 명명규칙은 xxxxImg으로 통일

import CarouselFirstImg from './CarouselFirstImg.png';
import CarouselSecondImg from './CarouselSecondImg.png';
import CarouselThirdImg from './CarouselThirdImg.png';
import ImgPost1 from './ImgPost1.png';
import ImgPost10 from './ImgPost10.png';
import ImgPost2 from './ImgPost2.png';
import ImgPost3 from './ImgPost3.png';
import ImgPost4 from './ImgPost4.png';
import ImgPost5 from './ImgPost5.png';
import ImgPost7 from './ImgPost7.png';
import ImgPost8 from './ImgPost8.png';
import ImgPost9 from './ImgPost9.png';
import ImgRec1 from './ImgRec1.png';
import ImgRec2 from './ImgRec2.png';
import ImgRec3 from './ImgRec3.png';
import ImgRec4 from './ImgRec4.png';
import ImgRec5 from './ImgRec5.png';
import ImgRec6 from './ImgRec6.png';
import ImgRec7 from './ImgRec7.png';
import RecommendFirstImg from './RecommendFirstImg.png';
import RecommendSecondImg from './RecommendSecondImg.png';

export { RecommendFirstImg };
export { RecommendSecondImg };
export { CarouselFirstImg };
export { CarouselSecondImg };
export { CarouselThirdImg };
export { ImgPost1 };
export { ImgPost2 };
export { ImgPost3 };
export { ImgPost4 };
export { ImgPost5 };
export { ImgRec1 };
export { ImgRec2 };
export { ImgRec3 };
export { ImgRec4 };
export { ImgRec5 };
export { ImgRec6 };
export { ImgRec7 };
export { ImgPost7 };
export { ImgPost8 };
export { ImgPost9 };
export { ImgPost10 };
// import {  RecommendFirstImg } from './RecommendFirstImg.png';
// import {  RecommendSecondImg } from './RecommendSecondImg.png';
// import {  CarouselFirstImg } from './CarouselFirstImg.png';
// import {  CarouselSecondImg }
// import {  CarouselThirdImg }
// import {  ImgPost1 } from './ImgPost1.png';
// import {  ImgPost2 } from './ImgPost2.png';
// import {  ImgPost3 } from './ImgPost3.png';
// import {  ImgPost4 } from './ImgPost4.png';
// import {  ImgPost5 } from './ImgPost5.png';
// import {  ImgRec1 } from './ImgRec1.png';
// import {  ImgRec2 } from './ImgRec2.png';
// import {  ImgRec3 } from './ImgRec3.png';
// import {  ImgRec4 } from './ImgRec4.png';
// import {  ImgRec5 } from './ImgRec5.png';
// import {  ImgRec6 } from './ImgRec6.png';
// import {  ImgRec7 } from './ImgRec7.png';
// import {  ImgPost7 } from './ImgPost7.png';
// import {  ImgPost8 } from './ImgPost8.png';
// import {  ImgPost9 } from './ImgPost9.png';
// import {  ImgPost10 } from './ImgPost10.png';
// import {  ImgPost11 } from './ImgPost11.png';
